name: Deploy to Custom Domain

on:
  push:
    branches:
      - main # Set this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Use the Node.js version that matches your project

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.8.1 # Use the version specified in your packageManager field

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build project
        run: pnpm run build

      - name: List build directory contents
        run: ls -la ./dist

      - name: Check if dist directory exists
        run: |
          if [ -d "./dist" ]; then
            echo "✅ dist directory exists"
            echo "Contents:"
            ls -la ./dist
          else
            echo "❌ dist directory does not exist"
            exit 1
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # The folder that contains your built static files
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'

      - name: Check gh-pages branch
        run: |
          git fetch origin gh-pages
          echo "Latest commit on gh-pages:"
          git log -1 --pretty=format:"%h - %an, %ar : %s" origin/gh-pages